/* Types for pwa.assets.mjs (GENERATED by scripts/make-screenshots.mjs),
   so vite.config.ts stays type-safe. Keep this shape in step with the
   generator — `form_factor: 'narrow'` is the phone layout only. */
export declare const screenshots: {
  readonly src: string
  readonly sizes: string
  readonly type: string
  readonly form_factor: 'narrow'
  readonly label: string
}[]
