/* GENERATED by scripts/make-screenshots.mjs — do not edit by hand.
   Regenerate with: node app/scripts/make-screenshots.mjs  (sizes come from the
   real PNGs, so the manifest can never claim a size the file does not have).
   Manifest screenshots (docs/08): what the install UI shows. */
export const screenshots = [
  {
    src: '/screenshots/narrow-language.png',
    sizes: '1170x2532',
    type: 'image/png',
    form_factor: 'narrow',
    label: 'Pick your language',
  },
  {
    src: '/screenshots/narrow-trips-add.png',
    sizes: '1170x2532',
    type: 'image/png',
    form_factor: 'narrow',
    label: 'Add your PNR and find a swap',
  },
]
