/* GENERATED by scripts/make-screenshots.mjs — do not edit by hand.
   Manifest screenshots (docs/08): what the install UI shows. */
export const screenshots = [
  {
    src: '/screenshots/narrow-language.png',
    sizes: '1170x2532',
    type: 'image/png',
    form_factor: 'narrow',
    label: "Pick your language",
  },
  {
    src: '/screenshots/narrow-trips-add.png',
    sizes: '1170x2532',
    type: 'image/png',
    form_factor: 'narrow',
    label: "Add your PNR and find a swap",
  }
]
