import { useEffect } from 'react'

/* Registers the service worker (docs/08-PWA-AND-TECH.md):
   - Never in dev or preview, never inside an iframe.
   - `?sw=off` is a kill switch that also unregisters what is there.
   The worker itself is generated by vite-plugin-pwa (generateSW). */
export function ServiceWorkerRegistrar() {
  useEffect(() => {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return

    const url = new URL(window.location.href)
    if (url.searchParams.get('sw') === 'off') {
      navigator.serviceWorker
        .getRegistrations()
        .then((registrations) => registrations.forEach((registration) => registration.unregister()))
        .catch(() => undefined)
      return
    }

    const host = window.location.hostname
    const isLocal =
      host === 'localhost' ||
      host === '127.0.0.1' ||
      host === '[::1]' ||
      host.startsWith('192.168.') ||
      host.startsWith('10.') ||
      host.endsWith('.local')

    let inFrame = false
    try {
      inFrame = window.self !== window.top
    } catch {
      inFrame = true
    }

    if (isLocal || inFrame || !/^https?:$/.test(window.location.protocol)) return

    const register = () => {
      navigator.serviceWorker.register('/sw.js').catch(() => undefined)
    }
    if (document.readyState === 'complete') register()
    else window.addEventListener('load', register, { once: true })
  }, [])

  return null
}
