/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckRouteImport } from './routes/check'
import { Route as GoodbyeRouteImport } from './routes/goodbye'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SwapsRouteImport } from './routes/swaps'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AdminIndexRouteImport } from './routes/admin._index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSwapsRouteImport } from './routes/admin.swaps'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as GroupsIdRouteImport } from './routes/groups.$id'
import { Route as IncomingIdRouteImport } from './routes/incoming.$id'
import { Route as OnboardTripIdRouteImport } from './routes/onboard.$tripId'
import { Route as PayRequestIdRouteImport } from './routes/pay.$requestId'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileDeleteRouteImport } from './routes/profile.delete'
import { Route as ProfileEasyRouteImport } from './routes/profile.easy'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfilePaymentsRouteImport } from './routes/profile.payments'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as RequestIdRouteImport } from './routes/request.$id'
import { Route as RequestNewRouteImport } from './routes/request.new'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as ShareTrainDateRouteImport } from './routes/share.$trainDate'
import { Route as SwapsIndexRouteImport } from './routes/swaps.index'
import { Route as TrainNumberRouteImport } from './routes/train.$number'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as TripsAddRouteImport } from './routes/trips.add'
import { Route as WelcomeAlertsRouteImport } from './routes/welcome.alerts'
import { Route as WelcomeLanguageRouteImport } from './routes/welcome.language'
import { Route as WelcomeNoteRouteImport } from './routes/welcome.note'
import { Route as WelcomePrivacyRouteImport } from './routes/welcome.privacy'
import { Route as GroupsIdIndexRouteImport } from './routes/groups.$id.index'
import { Route as GroupsIdPlanRouteImport } from './routes/groups.$id.plan'
import { Route as PayRequestIdIndexRouteImport } from './routes/pay.$requestId.index'
import { Route as PayRequestIdDoneRouteImport } from './routes/pay.$requestId.done'
import { Route as PayRequestIdMethodRouteImport } from './routes/pay.$requestId.method'
import { Route as PayRequestIdPaypalRouteImport } from './routes/pay.$requestId.paypal'
import { Route as PayRequestIdStatusRouteImport } from './routes/pay.$requestId.status'
import { Route as PayRequestIdUpiRouteImport } from './routes/pay.$requestId.upi'
import { Route as ProfilePaymentsIndexRouteImport } from './routes/profile.payments.index'
import { Route as ProfilePaymentsIdRouteImport } from './routes/profile.payments.$id'
import { Route as RequestIdIndexRouteImport } from './routes/request.$id.index'
import { Route as RequestIdMatchesRouteImport } from './routes/request.$id.matches'
import { Route as SwapsIdIndexRouteImport } from './routes/swaps.$id.index'
import { Route as SwapsIdCancelRouteImport } from './routes/swaps.$id.cancel'
import { Route as SwapsIdConfirmRouteImport } from './routes/swaps.$id.confirm'
import { Route as SwapsIdDoneRouteImport } from './routes/swaps.$id.done'
import { Route as SwapsIdMeetRouteImport } from './routes/swaps.$id.meet'
import { Route as SwapsIdRateRouteImport } from './routes/swaps.$id.rate'
import { Route as SwapsIdShareRouteImport } from './routes/swaps.$id.share'
import { Route as SwapsIdSummaryRouteImport } from './routes/swaps.$id.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapsRoute = SwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSwapsRoute = AdminSwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomingIdRoute = IncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTripIdRoute = OnboardTripIdRouteImport.update({
  id: '/onboard/$tripId',
  path: '/onboard/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRequestIdRoute = PayRequestIdRouteImport.update({
  id: '/pay/$requestId',
  path: '/pay/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileDeleteRoute = ProfileDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEasyRoute = ProfileEasyRouteImport.update({
  id: '/easy',
  path: '/easy',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentsRoute = ProfilePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const RequestIdRoute = RequestIdRouteImport.update({
  id: '/request/$id',
  path: '/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestNewRoute = RequestNewRouteImport.update({
  id: '/request/new',
  path: '/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTrainDateRoute = ShareTrainDateRouteImport.update({
  id: '/share/$trainDate',
  path: '/share/$trainDate',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapsIndexRoute = SwapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SwapsRoute,
} as any)
const TrainNumberRoute = TrainNumberRouteImport.update({
  id: '/train/$number',
  path: '/train/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsAddRoute = TripsAddRouteImport.update({
  id: '/trips/add',
  path: '/trips/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeAlertsRoute = WelcomeAlertsRouteImport.update({
  id: '/welcome/alerts',
  path: '/welcome/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeLanguageRoute = WelcomeLanguageRouteImport.update({
  id: '/welcome/language',
  path: '/welcome/language',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeNoteRoute = WelcomeNoteRouteImport.update({
  id: '/welcome/note',
  path: '/welcome/note',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomePrivacyRoute = WelcomePrivacyRouteImport.update({
  id: '/welcome/privacy',
  path: '/welcome/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdIndexRoute = GroupsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsIdRoute,
} as any)
const GroupsIdPlanRoute = GroupsIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => GroupsIdRoute,
} as any)
const PayRequestIdIndexRoute = PayRequestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const PayRequestIdDoneRoute = PayRequestIdDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const PayRequestIdMethodRoute = PayRequestIdMethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const PayRequestIdPaypalRoute = PayRequestIdPaypalRouteImport.update({
  id: '/paypal',
  path: '/paypal',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const PayRequestIdStatusRoute = PayRequestIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const PayRequestIdUpiRoute = PayRequestIdUpiRouteImport.update({
  id: '/upi',
  path: '/upi',
  getParentRoute: () => PayRequestIdRoute,
} as any)
const ProfilePaymentsIndexRoute = ProfilePaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfilePaymentsRoute,
} as any)
const ProfilePaymentsIdRoute = ProfilePaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProfilePaymentsRoute,
} as any)
const RequestIdIndexRoute = RequestIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestIdRoute,
} as any)
const RequestIdMatchesRoute = RequestIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => RequestIdRoute,
} as any)
const SwapsIdIndexRoute = SwapsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdCancelRoute = SwapsIdCancelRouteImport.update({
  id: '/$id/cancel',
  path: '/$id/cancel',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdConfirmRoute = SwapsIdConfirmRouteImport.update({
  id: '/$id/confirm',
  path: '/$id/confirm',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdDoneRoute = SwapsIdDoneRouteImport.update({
  id: '/$id/done',
  path: '/$id/done',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdMeetRoute = SwapsIdMeetRouteImport.update({
  id: '/$id/meet',
  path: '/$id/meet',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdRateRoute = SwapsIdRateRouteImport.update({
  id: '/$id/rate',
  path: '/$id/rate',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdShareRoute = SwapsIdShareRouteImport.update({
  id: '/$id/share',
  path: '/$id/share',
  getParentRoute: () => SwapsRoute,
} as any)
const SwapsIdSummaryRoute = SwapsIdSummaryRouteImport.update({
  id: '/$id/summary',
  path: '/$id/summary',
  getParentRoute: () => SwapsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check': typeof CheckRoute
  '/goodbye': typeof GoodbyeRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signin': typeof SigninRoute
  '/swaps': typeof SwapsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/swaps': typeof AdminSwapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/incoming/$id': typeof IncomingIdRoute
  '/onboard/$tripId': typeof OnboardTripIdRoute
  '/pay/$requestId': typeof PayRequestIdRouteWithChildren
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/easy': typeof ProfileEasyRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/payments': typeof ProfilePaymentsRouteWithChildren
  '/profile/settings': typeof ProfileSettingsRoute
  '/request/$id': typeof RequestIdRouteWithChildren
  '/request/new': typeof RequestNewRoute
  '/s/$code': typeof SCodeRoute
  '/share/$trainDate': typeof ShareTrainDateRoute
  '/train/$number': typeof TrainNumberRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
  '/profile/': typeof ProfileIndexRoute
  '/swaps/': typeof SwapsIndexRoute
  '/groups/$id/plan': typeof GroupsIdPlanRoute
  '/pay/$requestId/done': typeof PayRequestIdDoneRoute
  '/pay/$requestId/method': typeof PayRequestIdMethodRoute
  '/pay/$requestId/paypal': typeof PayRequestIdPaypalRoute
  '/pay/$requestId/status': typeof PayRequestIdStatusRoute
  '/pay/$requestId/upi': typeof PayRequestIdUpiRoute
  '/profile/payments/$id': typeof ProfilePaymentsIdRoute
  '/request/$id/matches': typeof RequestIdMatchesRoute
  '/swaps/$id/cancel': typeof SwapsIdCancelRoute
  '/swaps/$id/confirm': typeof SwapsIdConfirmRoute
  '/swaps/$id/done': typeof SwapsIdDoneRoute
  '/swaps/$id/meet': typeof SwapsIdMeetRoute
  '/swaps/$id/rate': typeof SwapsIdRateRoute
  '/swaps/$id/share': typeof SwapsIdShareRoute
  '/swaps/$id/summary': typeof SwapsIdSummaryRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/pay/$requestId/': typeof PayRequestIdIndexRoute
  '/profile/payments/': typeof ProfilePaymentsIndexRoute
  '/request/$id/': typeof RequestIdIndexRoute
  '/swaps/$id/': typeof SwapsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check': typeof CheckRoute
  '/goodbye': typeof GoodbyeRoute
  '/signin': typeof SigninRoute
  '/updates': typeof UpdatesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/swaps': typeof AdminSwapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/incoming/$id': typeof IncomingIdRoute
  '/onboard/$tripId': typeof OnboardTripIdRoute
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/easy': typeof ProfileEasyRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/request/new': typeof RequestNewRoute
  '/s/$code': typeof SCodeRoute
  '/share/$trainDate': typeof ShareTrainDateRoute
  '/train/$number': typeof TrainNumberRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
  '/profile': typeof ProfileIndexRoute
  '/swaps': typeof SwapsIndexRoute
  '/groups/$id/plan': typeof GroupsIdPlanRoute
  '/pay/$requestId/done': typeof PayRequestIdDoneRoute
  '/pay/$requestId/method': typeof PayRequestIdMethodRoute
  '/pay/$requestId/paypal': typeof PayRequestIdPaypalRoute
  '/pay/$requestId/status': typeof PayRequestIdStatusRoute
  '/pay/$requestId/upi': typeof PayRequestIdUpiRoute
  '/profile/payments/$id': typeof ProfilePaymentsIdRoute
  '/request/$id/matches': typeof RequestIdMatchesRoute
  '/swaps/$id/cancel': typeof SwapsIdCancelRoute
  '/swaps/$id/confirm': typeof SwapsIdConfirmRoute
  '/swaps/$id/done': typeof SwapsIdDoneRoute
  '/swaps/$id/meet': typeof SwapsIdMeetRoute
  '/swaps/$id/rate': typeof SwapsIdRateRoute
  '/swaps/$id/share': typeof SwapsIdShareRoute
  '/swaps/$id/summary': typeof SwapsIdSummaryRoute
  '/groups/$id': typeof GroupsIdIndexRoute
  '/pay/$requestId': typeof PayRequestIdIndexRoute
  '/profile/payments': typeof ProfilePaymentsIndexRoute
  '/request/$id': typeof RequestIdIndexRoute
  '/swaps/$id': typeof SwapsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/check': typeof CheckRoute
  '/goodbye': typeof GoodbyeRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signin': typeof SigninRoute
  '/swaps': typeof SwapsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/admin/_index': typeof AdminIndexRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/swaps': typeof AdminSwapsRoute
  '/admin/users': typeof AdminUsersRoute
  '/chat/$id': typeof ChatIdRoute
  '/groups/$id': typeof GroupsIdRouteWithChildren
  '/incoming/$id': typeof IncomingIdRoute
  '/onboard/$tripId': typeof OnboardTripIdRoute
  '/pay/$requestId': typeof PayRequestIdRouteWithChildren
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/easy': typeof ProfileEasyRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/payments': typeof ProfilePaymentsRouteWithChildren
  '/profile/settings': typeof ProfileSettingsRoute
  '/request/$id': typeof RequestIdRouteWithChildren
  '/request/new': typeof RequestNewRoute
  '/s/$code': typeof SCodeRoute
  '/share/$trainDate': typeof ShareTrainDateRoute
  '/train/$number': typeof TrainNumberRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
  '/profile/': typeof ProfileIndexRoute
  '/swaps/': typeof SwapsIndexRoute
  '/groups/$id/plan': typeof GroupsIdPlanRoute
  '/pay/$requestId/done': typeof PayRequestIdDoneRoute
  '/pay/$requestId/method': typeof PayRequestIdMethodRoute
  '/pay/$requestId/paypal': typeof PayRequestIdPaypalRoute
  '/pay/$requestId/status': typeof PayRequestIdStatusRoute
  '/pay/$requestId/upi': typeof PayRequestIdUpiRoute
  '/profile/payments/$id': typeof ProfilePaymentsIdRoute
  '/request/$id/matches': typeof RequestIdMatchesRoute
  '/swaps/$id/cancel': typeof SwapsIdCancelRoute
  '/swaps/$id/confirm': typeof SwapsIdConfirmRoute
  '/swaps/$id/done': typeof SwapsIdDoneRoute
  '/swaps/$id/meet': typeof SwapsIdMeetRoute
  '/swaps/$id/rate': typeof SwapsIdRateRoute
  '/swaps/$id/share': typeof SwapsIdShareRoute
  '/swaps/$id/summary': typeof SwapsIdSummaryRoute
  '/groups/$id/': typeof GroupsIdIndexRoute
  '/pay/$requestId/': typeof PayRequestIdIndexRoute
  '/profile/payments/': typeof ProfilePaymentsIndexRoute
  '/request/$id/': typeof RequestIdIndexRoute
  '/swaps/$id/': typeof SwapsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/check'
    | '/goodbye'
    | '/profile'
    | '/signin'
    | '/swaps'
    | '/updates'
    | '/admin/activity'
    | '/admin/credits'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/swaps'
    | '/admin/users'
    | '/chat/$id'
    | '/groups/$id'
    | '/incoming/$id'
    | '/onboard/$tripId'
    | '/pay/$requestId'
    | '/profile/delete'
    | '/profile/easy'
    | '/profile/help'
    | '/profile/payments'
    | '/profile/settings'
    | '/request/$id'
    | '/request/new'
    | '/s/$code'
    | '/share/$trainDate'
    | '/train/$number'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
    | '/profile/'
    | '/swaps/'
    | '/groups/$id/plan'
    | '/pay/$requestId/done'
    | '/pay/$requestId/method'
    | '/pay/$requestId/paypal'
    | '/pay/$requestId/status'
    | '/pay/$requestId/upi'
    | '/profile/payments/$id'
    | '/request/$id/matches'
    | '/swaps/$id/cancel'
    | '/swaps/$id/confirm'
    | '/swaps/$id/done'
    | '/swaps/$id/meet'
    | '/swaps/$id/rate'
    | '/swaps/$id/share'
    | '/swaps/$id/summary'
    | '/groups/$id/'
    | '/pay/$requestId/'
    | '/profile/payments/'
    | '/request/$id/'
    | '/swaps/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/check'
    | '/goodbye'
    | '/signin'
    | '/updates'
    | '/admin/activity'
    | '/admin/credits'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/swaps'
    | '/admin/users'
    | '/chat/$id'
    | '/incoming/$id'
    | '/onboard/$tripId'
    | '/profile/delete'
    | '/profile/easy'
    | '/profile/help'
    | '/profile/settings'
    | '/request/new'
    | '/s/$code'
    | '/share/$trainDate'
    | '/train/$number'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
    | '/profile'
    | '/swaps'
    | '/groups/$id/plan'
    | '/pay/$requestId/done'
    | '/pay/$requestId/method'
    | '/pay/$requestId/paypal'
    | '/pay/$requestId/status'
    | '/pay/$requestId/upi'
    | '/profile/payments/$id'
    | '/request/$id/matches'
    | '/swaps/$id/cancel'
    | '/swaps/$id/confirm'
    | '/swaps/$id/done'
    | '/swaps/$id/meet'
    | '/swaps/$id/rate'
    | '/swaps/$id/share'
    | '/swaps/$id/summary'
    | '/groups/$id'
    | '/pay/$requestId'
    | '/profile/payments'
    | '/request/$id'
    | '/swaps/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/check'
    | '/goodbye'
    | '/profile'
    | '/signin'
    | '/swaps'
    | '/updates'
    | '/admin/_index'
    | '/admin/activity'
    | '/admin/credits'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/swaps'
    | '/admin/users'
    | '/chat/$id'
    | '/groups/$id'
    | '/incoming/$id'
    | '/onboard/$tripId'
    | '/pay/$requestId'
    | '/profile/delete'
    | '/profile/easy'
    | '/profile/help'
    | '/profile/payments'
    | '/profile/settings'
    | '/request/$id'
    | '/request/new'
    | '/s/$code'
    | '/share/$trainDate'
    | '/train/$number'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
    | '/profile/'
    | '/swaps/'
    | '/groups/$id/plan'
    | '/pay/$requestId/done'
    | '/pay/$requestId/method'
    | '/pay/$requestId/paypal'
    | '/pay/$requestId/status'
    | '/pay/$requestId/upi'
    | '/profile/payments/$id'
    | '/request/$id/matches'
    | '/swaps/$id/cancel'
    | '/swaps/$id/confirm'
    | '/swaps/$id/done'
    | '/swaps/$id/meet'
    | '/swaps/$id/rate'
    | '/swaps/$id/share'
    | '/swaps/$id/summary'
    | '/groups/$id/'
    | '/pay/$requestId/'
    | '/profile/payments/'
    | '/request/$id/'
    | '/swaps/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckRoute: typeof CheckRoute
  GoodbyeRoute: typeof GoodbyeRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SigninRoute: typeof SigninRoute
  SwapsRoute: typeof SwapsRouteWithChildren
  UpdatesRoute: typeof UpdatesRoute
  ChatIdRoute: typeof ChatIdRoute
  GroupsIdRoute: typeof GroupsIdRouteWithChildren
  IncomingIdRoute: typeof IncomingIdRoute
  OnboardTripIdRoute: typeof OnboardTripIdRoute
  PayRequestIdRoute: typeof PayRequestIdRouteWithChildren
  RequestIdRoute: typeof RequestIdRouteWithChildren
  RequestNewRoute: typeof RequestNewRoute
  SCodeRoute: typeof SCodeRoute
  ShareTrainDateRoute: typeof ShareTrainDateRoute
  TrainNumberRoute: typeof TrainNumberRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsAddRoute: typeof TripsAddRoute
  WelcomeAlertsRoute: typeof WelcomeAlertsRoute
  WelcomeLanguageRoute: typeof WelcomeLanguageRoute
  WelcomeNoteRoute: typeof WelcomeNoteRoute
  WelcomePrivacyRoute: typeof WelcomePrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swaps': {
      id: '/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof SwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_index': {
      id: '/admin/_index'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/swaps': {
      id: '/admin/swaps'
      path: '/swaps'
      fullPath: '/admin/swaps'
      preLoaderRoute: typeof AdminSwapsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incoming/$id': {
      id: '/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof IncomingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$tripId': {
      id: '/onboard/$tripId'
      path: '/onboard/$tripId'
      fullPath: '/onboard/$tripId'
      preLoaderRoute: typeof OnboardTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$requestId': {
      id: '/pay/$requestId'
      path: '/pay/$requestId'
      fullPath: '/pay/$requestId'
      preLoaderRoute: typeof PayRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/delete': {
      id: '/profile/delete'
      path: '/delete'
      fullPath: '/profile/delete'
      preLoaderRoute: typeof ProfileDeleteRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/easy': {
      id: '/profile/easy'
      path: '/easy'
      fullPath: '/profile/easy'
      preLoaderRoute: typeof ProfileEasyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payments': {
      id: '/profile/payments'
      path: '/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof ProfilePaymentsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/request/$id': {
      id: '/request/$id'
      path: '/request/$id'
      fullPath: '/request/$id'
      preLoaderRoute: typeof RequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/new': {
      id: '/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof RequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$trainDate': {
      id: '/share/$trainDate'
      path: '/share/$trainDate'
      fullPath: '/share/$trainDate'
      preLoaderRoute: typeof ShareTrainDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swaps/': {
      id: '/swaps/'
      path: '/'
      fullPath: '/swaps/'
      preLoaderRoute: typeof SwapsIndexRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/train/$number': {
      id: '/train/$number'
      path: '/train/$number'
      fullPath: '/train/$number'
      preLoaderRoute: typeof TrainNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/add': {
      id: '/trips/add'
      path: '/trips/add'
      fullPath: '/trips/add'
      preLoaderRoute: typeof TripsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/alerts': {
      id: '/welcome/alerts'
      path: '/welcome/alerts'
      fullPath: '/welcome/alerts'
      preLoaderRoute: typeof WelcomeAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/language': {
      id: '/welcome/language'
      path: '/welcome/language'
      fullPath: '/welcome/language'
      preLoaderRoute: typeof WelcomeLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/note': {
      id: '/welcome/note'
      path: '/welcome/note'
      fullPath: '/welcome/note'
      preLoaderRoute: typeof WelcomeNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/privacy': {
      id: '/welcome/privacy'
      path: '/welcome/privacy'
      fullPath: '/welcome/privacy'
      preLoaderRoute: typeof WelcomePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id/': {
      id: '/groups/$id/'
      path: '/'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof GroupsIdIndexRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/groups/$id/plan': {
      id: '/groups/$id/plan'
      path: '/plan'
      fullPath: '/groups/$id/plan'
      preLoaderRoute: typeof GroupsIdPlanRouteImport
      parentRoute: typeof GroupsIdRoute
    }
    '/pay/$requestId/': {
      id: '/pay/$requestId/'
      path: '/'
      fullPath: '/pay/$requestId/'
      preLoaderRoute: typeof PayRequestIdIndexRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/pay/$requestId/done': {
      id: '/pay/$requestId/done'
      path: '/done'
      fullPath: '/pay/$requestId/done'
      preLoaderRoute: typeof PayRequestIdDoneRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/pay/$requestId/method': {
      id: '/pay/$requestId/method'
      path: '/method'
      fullPath: '/pay/$requestId/method'
      preLoaderRoute: typeof PayRequestIdMethodRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/pay/$requestId/paypal': {
      id: '/pay/$requestId/paypal'
      path: '/paypal'
      fullPath: '/pay/$requestId/paypal'
      preLoaderRoute: typeof PayRequestIdPaypalRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/pay/$requestId/status': {
      id: '/pay/$requestId/status'
      path: '/status'
      fullPath: '/pay/$requestId/status'
      preLoaderRoute: typeof PayRequestIdStatusRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/pay/$requestId/upi': {
      id: '/pay/$requestId/upi'
      path: '/upi'
      fullPath: '/pay/$requestId/upi'
      preLoaderRoute: typeof PayRequestIdUpiRouteImport
      parentRoute: typeof PayRequestIdRoute
    }
    '/profile/payments/': {
      id: '/profile/payments/'
      path: '/'
      fullPath: '/profile/payments/'
      preLoaderRoute: typeof ProfilePaymentsIndexRouteImport
      parentRoute: typeof ProfilePaymentsRoute
    }
    '/profile/payments/$id': {
      id: '/profile/payments/$id'
      path: '/$id'
      fullPath: '/profile/payments/$id'
      preLoaderRoute: typeof ProfilePaymentsIdRouteImport
      parentRoute: typeof ProfilePaymentsRoute
    }
    '/request/$id/': {
      id: '/request/$id/'
      path: '/'
      fullPath: '/request/$id/'
      preLoaderRoute: typeof RequestIdIndexRouteImport
      parentRoute: typeof RequestIdRoute
    }
    '/request/$id/matches': {
      id: '/request/$id/matches'
      path: '/matches'
      fullPath: '/request/$id/matches'
      preLoaderRoute: typeof RequestIdMatchesRouteImport
      parentRoute: typeof RequestIdRoute
    }
    '/swaps/$id/': {
      id: '/swaps/$id/'
      path: '/$id'
      fullPath: '/swaps/$id/'
      preLoaderRoute: typeof SwapsIdIndexRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/cancel': {
      id: '/swaps/$id/cancel'
      path: '/$id/cancel'
      fullPath: '/swaps/$id/cancel'
      preLoaderRoute: typeof SwapsIdCancelRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/confirm': {
      id: '/swaps/$id/confirm'
      path: '/$id/confirm'
      fullPath: '/swaps/$id/confirm'
      preLoaderRoute: typeof SwapsIdConfirmRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/done': {
      id: '/swaps/$id/done'
      path: '/$id/done'
      fullPath: '/swaps/$id/done'
      preLoaderRoute: typeof SwapsIdDoneRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/meet': {
      id: '/swaps/$id/meet'
      path: '/$id/meet'
      fullPath: '/swaps/$id/meet'
      preLoaderRoute: typeof SwapsIdMeetRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/rate': {
      id: '/swaps/$id/rate'
      path: '/$id/rate'
      fullPath: '/swaps/$id/rate'
      preLoaderRoute: typeof SwapsIdRateRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/share': {
      id: '/swaps/$id/share'
      path: '/$id/share'
      fullPath: '/swaps/$id/share'
      preLoaderRoute: typeof SwapsIdShareRouteImport
      parentRoute: typeof SwapsRoute
    }
    '/swaps/$id/summary': {
      id: '/swaps/$id/summary'
      path: '/$id/summary'
      fullPath: '/swaps/$id/summary'
      preLoaderRoute: typeof SwapsIdSummaryRouteImport
      parentRoute: typeof SwapsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSwapsRoute: typeof AdminSwapsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSwapsRoute: AdminSwapsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfilePaymentsRouteChildren {
  ProfilePaymentsIdRoute: typeof ProfilePaymentsIdRoute
  ProfilePaymentsIndexRoute: typeof ProfilePaymentsIndexRoute
}

const ProfilePaymentsRouteChildren: ProfilePaymentsRouteChildren = {
  ProfilePaymentsIdRoute: ProfilePaymentsIdRoute,
  ProfilePaymentsIndexRoute: ProfilePaymentsIndexRoute,
}

const ProfilePaymentsRouteWithChildren = ProfilePaymentsRoute._addFileChildren(
  ProfilePaymentsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileDeleteRoute: typeof ProfileDeleteRoute
  ProfileEasyRoute: typeof ProfileEasyRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfilePaymentsRoute: typeof ProfilePaymentsRouteWithChildren
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileDeleteRoute: ProfileDeleteRoute,
  ProfileEasyRoute: ProfileEasyRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfilePaymentsRoute: ProfilePaymentsRouteWithChildren,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface SwapsRouteChildren {
  SwapsIndexRoute: typeof SwapsIndexRoute
  SwapsIdCancelRoute: typeof SwapsIdCancelRoute
  SwapsIdConfirmRoute: typeof SwapsIdConfirmRoute
  SwapsIdDoneRoute: typeof SwapsIdDoneRoute
  SwapsIdMeetRoute: typeof SwapsIdMeetRoute
  SwapsIdRateRoute: typeof SwapsIdRateRoute
  SwapsIdShareRoute: typeof SwapsIdShareRoute
  SwapsIdSummaryRoute: typeof SwapsIdSummaryRoute
  SwapsIdIndexRoute: typeof SwapsIdIndexRoute
}

const SwapsRouteChildren: SwapsRouteChildren = {
  SwapsIndexRoute: SwapsIndexRoute,
  SwapsIdCancelRoute: SwapsIdCancelRoute,
  SwapsIdConfirmRoute: SwapsIdConfirmRoute,
  SwapsIdDoneRoute: SwapsIdDoneRoute,
  SwapsIdMeetRoute: SwapsIdMeetRoute,
  SwapsIdRateRoute: SwapsIdRateRoute,
  SwapsIdShareRoute: SwapsIdShareRoute,
  SwapsIdSummaryRoute: SwapsIdSummaryRoute,
  SwapsIdIndexRoute: SwapsIdIndexRoute,
}

const SwapsRouteWithChildren = SwapsRoute._addFileChildren(SwapsRouteChildren)

interface GroupsIdRouteChildren {
  GroupsIdPlanRoute: typeof GroupsIdPlanRoute
  GroupsIdIndexRoute: typeof GroupsIdIndexRoute
}

const GroupsIdRouteChildren: GroupsIdRouteChildren = {
  GroupsIdPlanRoute: GroupsIdPlanRoute,
  GroupsIdIndexRoute: GroupsIdIndexRoute,
}

const GroupsIdRouteWithChildren = GroupsIdRoute._addFileChildren(
  GroupsIdRouteChildren,
)

interface PayRequestIdRouteChildren {
  PayRequestIdDoneRoute: typeof PayRequestIdDoneRoute
  PayRequestIdMethodRoute: typeof PayRequestIdMethodRoute
  PayRequestIdPaypalRoute: typeof PayRequestIdPaypalRoute
  PayRequestIdStatusRoute: typeof PayRequestIdStatusRoute
  PayRequestIdUpiRoute: typeof PayRequestIdUpiRoute
  PayRequestIdIndexRoute: typeof PayRequestIdIndexRoute
}

const PayRequestIdRouteChildren: PayRequestIdRouteChildren = {
  PayRequestIdDoneRoute: PayRequestIdDoneRoute,
  PayRequestIdMethodRoute: PayRequestIdMethodRoute,
  PayRequestIdPaypalRoute: PayRequestIdPaypalRoute,
  PayRequestIdStatusRoute: PayRequestIdStatusRoute,
  PayRequestIdUpiRoute: PayRequestIdUpiRoute,
  PayRequestIdIndexRoute: PayRequestIdIndexRoute,
}

const PayRequestIdRouteWithChildren = PayRequestIdRoute._addFileChildren(
  PayRequestIdRouteChildren,
)

interface RequestIdRouteChildren {
  RequestIdMatchesRoute: typeof RequestIdMatchesRoute
  RequestIdIndexRoute: typeof RequestIdIndexRoute
}

const RequestIdRouteChildren: RequestIdRouteChildren = {
  RequestIdMatchesRoute: RequestIdMatchesRoute,
  RequestIdIndexRoute: RequestIdIndexRoute,
}

const RequestIdRouteWithChildren = RequestIdRoute._addFileChildren(
  RequestIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckRoute: CheckRoute,
  GoodbyeRoute: GoodbyeRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SigninRoute: SigninRoute,
  SwapsRoute: SwapsRouteWithChildren,
  UpdatesRoute: UpdatesRoute,
  ChatIdRoute: ChatIdRoute,
  GroupsIdRoute: GroupsIdRouteWithChildren,
  IncomingIdRoute: IncomingIdRoute,
  OnboardTripIdRoute: OnboardTripIdRoute,
  PayRequestIdRoute: PayRequestIdRouteWithChildren,
  RequestIdRoute: RequestIdRouteWithChildren,
  RequestNewRoute: RequestNewRoute,
  SCodeRoute: SCodeRoute,
  ShareTrainDateRoute: ShareTrainDateRoute,
  TrainNumberRoute: TrainNumberRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsAddRoute: TripsAddRoute,
  WelcomeAlertsRoute: WelcomeAlertsRoute,
  WelcomeLanguageRoute: WelcomeLanguageRoute,
  WelcomeNoteRoute: WelcomeNoteRoute,
  WelcomePrivacyRoute: WelcomePrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
