/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SwapsRouteImport } from './routes/swaps'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'
import { Route as TripsAddRouteImport } from './routes/trips.add'
import { Route as WelcomeAlertsRouteImport } from './routes/welcome.alerts'
import { Route as WelcomeLanguageRouteImport } from './routes/welcome.language'
import { Route as WelcomeNoteRouteImport } from './routes/welcome.note'
import { Route as WelcomePrivacyRouteImport } from './routes/welcome.privacy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapsRoute = SwapsRouteImport.update({
  id: '/swaps',
  path: '/swaps',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsAddRoute = TripsAddRouteImport.update({
  id: '/trips/add',
  path: '/trips/add',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeAlertsRoute = WelcomeAlertsRouteImport.update({
  id: '/welcome/alerts',
  path: '/welcome/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeLanguageRoute = WelcomeLanguageRouteImport.update({
  id: '/welcome/language',
  path: '/welcome/language',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeNoteRoute = WelcomeNoteRouteImport.update({
  id: '/welcome/note',
  path: '/welcome/note',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomePrivacyRoute = WelcomePrivacyRouteImport.update({
  id: '/welcome/privacy',
  path: '/welcome/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/swaps': typeof SwapsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/swaps': typeof SwapsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/swaps': typeof SwapsRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/trips/add': typeof TripsAddRoute
  '/welcome/alerts': typeof WelcomeAlertsRoute
  '/welcome/language': typeof WelcomeLanguageRoute
  '/welcome/note': typeof WelcomeNoteRoute
  '/welcome/privacy': typeof WelcomePrivacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/signin'
    | '/swaps'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/signin'
    | '/swaps'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/signin'
    | '/swaps'
    | '/trips/$tripId'
    | '/trips/add'
    | '/welcome/alerts'
    | '/welcome/language'
    | '/welcome/note'
    | '/welcome/privacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SwapsRoute: typeof SwapsRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  TripsAddRoute: typeof TripsAddRoute
  WelcomeAlertsRoute: typeof WelcomeAlertsRoute
  WelcomeLanguageRoute: typeof WelcomeLanguageRoute
  WelcomeNoteRoute: typeof WelcomeNoteRoute
  WelcomePrivacyRoute: typeof WelcomePrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swaps': {
      id: '/swaps'
      path: '/swaps'
      fullPath: '/swaps'
      preLoaderRoute: typeof SwapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/add': {
      id: '/trips/add'
      path: '/trips/add'
      fullPath: '/trips/add'
      preLoaderRoute: typeof TripsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/alerts': {
      id: '/welcome/alerts'
      path: '/welcome/alerts'
      fullPath: '/welcome/alerts'
      preLoaderRoute: typeof WelcomeAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/language': {
      id: '/welcome/language'
      path: '/welcome/language'
      fullPath: '/welcome/language'
      preLoaderRoute: typeof WelcomeLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/note': {
      id: '/welcome/note'
      path: '/welcome/note'
      fullPath: '/welcome/note'
      preLoaderRoute: typeof WelcomeNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/privacy': {
      id: '/welcome/privacy'
      path: '/welcome/privacy'
      fullPath: '/welcome/privacy'
      preLoaderRoute: typeof WelcomePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SwapsRoute: SwapsRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  TripsAddRoute: TripsAddRoute,
  WelcomeAlertsRoute: WelcomeAlertsRoute,
  WelcomeLanguageRoute: WelcomeLanguageRoute,
  WelcomeNoteRoute: WelcomeNoteRoute,
  WelcomePrivacyRoute: WelcomePrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
