/* Post-build steps (see app/pwa.workbox.mjs for why the worker lives here):
   1. Generate the service worker with workbox-build `generateSW`, using the
      shared options from app/pwa.workbox.mjs. Running after `vite build` means
      the prerendered SPA shell (dist/client/index.html) is already on disk.
   2. 404.html: GitHub Pages serves it for unknown paths, so deep links like
      /trips/abc boot the SPA shell.
   3. .nojekyll: stop Pages from filtering files that start with an underscore. */
import { copyFileSync, existsSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { swFilename, workboxOptions } from '../pwa.workbox.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist', 'client')
const shell = join(dist, 'index.html')
const swDest = join(dist, swFilename)

if (!existsSync(shell)) {
  console.error('[postbuild] dist/client/index.html is missing — the SPA shell did not build.')
  process.exit(1)
}

/* 1. Service worker --------------------------------------------------- */
if (existsSync(swDest)) {
  console.log('[postbuild] sw.js already generated by the build — keeping it.')
} else {
  const { generateSW } = await import('workbox-build')
  const { count, size, warnings } = await generateSW({
    ...workboxOptions,
    globDirectory: dist,
    swDest,
    mode: 'production',
  })
  for (const warning of warnings) console.warn(`[postbuild] sw warning: ${warning}`)
  console.log(
    `[postbuild] ${swFilename}: precached ${count} files (${(size / 1024).toFixed(1)} KB precache).`,
  )
}

/* 2 + 3. Static-host touches ------------------------------------------ */
copyFileSync(shell, join(dist, '404.html'))
writeFileSync(join(dist, '.nojekyll'), '')
console.log('[postbuild] wrote dist/client/404.html and dist/client/.nojekyll')
